lh: use client-server architecture
We move the path shortening logic to an Elixir server as a NIF, then
rename the previous "lh" binary to "lhc" to denote that it acts as a
thin client.

This is grossly over-engineered but it is a nice "hello world" demo of
how Elixir NIFs can work.

Unfortunately, on NixOS we are forced to use the "--debug" flag when
installing the lhc binary because otherwise we get an obscure glibc
error, like this:

    [nix-shell:~/syscfg/lhc]$ cargo install --path .
      Installing lhc v0.1.0 (/home/l/syscfg/lhc)
          Updating crates.io index
             Compiling serde v1.0.130
                Compiling clap v3.0.0-beta.5
                error:
                /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6:
                version `GLIBC_2.33' not found (required by
                /home/l/syscfg/lhc/target/release/deps/libserde_derive-edb4fd996df6d324.so)
                   -->
                   /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.130/src/lib.rs:293:1
                       |
                       293 | extern crate serde_derive;
                           | ^^^^^^^^^^^^^^^^^^^^^^^^^^

    error: could not compile `serde` due to previous error
    warning: build failed, waiting for other jobs to finish...
    error:
    /nix/store/gk42f59363p82rg2wv2mfy71jn5w4q4c-glibc-2.32-48/lib/libc.so.6:
    version `GLIBC_2.33' not found (required by
    /home/l/syscfg/lhc/target/release/deps/libclap_derive-9f3e0104172da32d.so)
      -->
      /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.5/src/lib.rs:43:9
         |
         43 | pub use clap_derive::{self, *};
            |         ^^^^^^^^^^^

    error: failed to compile `lhc v0.1.0 (/home/l/syscfg/lhc)`, intermediate
    artifacts can be found at `/home/l/syscfg/lhc/target`

    Caused by:
      build failed

And I'm too lazy to debug this.