nix: chromium: remove unsupported option
Apparently this was enabled by default since Nixos 14.12 (2014!). I
suppose some recent change to nix made it so that unsupported options
now throw an error. Anyway, with this change, we can do

	nix-channel --update
	nix-env -qaP

Without this change, the "nix-env -qaP" would fail with:

	warning: name collision in input Nix expressions, skipping '/home/l/.nix-defexpr/channels_root/nixos'
	error: anonymous function at /nix/store/17270scb1ix6rgq62in9clrd7a8n049a-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/pkgs/applications/networking/browsers/chromium/default.nix:1:1 called with unexpected argument 'enablePepperPDF', at /nix/store/17270scb1ix6rgq62in9clrd7a8n049a-nixpkgs-19.09pre174594.0c0954781e2/nixpkgs/lib/customisation.nix:69:12